#+TITLE: Learning Machine
#+AUTHOR: Haoyang Xu

黄墙红瓦，深色窗框。我看到这幢房子，就料到这是罗晨的家。在一片白墙蓝窗的地中海风格豪华住宅区里，它显得独树一帜，这就是罗晨的风格。我放慢了车速，朝大门里张望，他果然就在门廊笑着朝我招手。

我告诉有点昏昏欲睡的妻子：“到了。”然后把车倒回一点，左转开进罗晨家的院子里。

罗晨带着我们穿过正门，走进下沉式的客厅。“来的路上还顺利吧？”他问。“很快，高速不堵车，一口气就开到了。”我说。

罗晨招呼我和妻子在双人沙发上坐下，自己坐在茶几一头的单人沙发上。罗晨的妻子敏惠出来和我们打了招呼，又到厨房里去忙了。

妻子说：“你们聊，我去看看她要不要帮忙。”

不一会儿，妻子端着茶具，敏惠抬着一盘刚烤好的饼干，小心地把它们放在茶几上。敏惠在罗晨对面的单人沙发上坐下，眼睛低垂。妻子又在我旁边坐下。

我拿起饼干，咬了一口。浓郁的黄油和鸡蛋香味充满了我的口腔。没来得及多想，我吃完了一大块。

罗晨却不太满意：“怎么又是黄油饼干？”

敏惠说：“因为最近几次你都说很喜欢吃，所以我多买了点材料，准备多做一些给你们吃的。”

罗晨揉了揉脑门，说：“那也不能天天吃吧。昨天张老板来，我们两个才吃了一大盘，今天我还以为你会换点儿花样呢。”

我喝了一口茶，对罗晨说：“别怪你家敏惠了，自己家做的黄油饼干，能烤得这么好吃也不容易。我还挺喜欢的，让我想起小时候吃过的饼干了。”

罗晨对敏惠说：“好了，帮我洗点水果来吧，这么饱肚子的饼干我是不能多吃了。”这样说着，他也拿了一块。“你还记得以前学校旁边的糕饼店吗？”

我笑了：“怎么不记得，我整个中学六年就吃过一次饼干，就是他们家的，而且还没给钱！”

罗晨说：“我也就吃过那一次。”他端起茶喝了一口，把嘴里的饼干渣漱下去。“那老板也真是的，把糕饼店开在我们学校门口，明明知道没几个学生买得起，还每天一大清早就开门。我有时候早饭钱被高年级的同学抢了，饿着肚子，一边闻着蛋糕味一边上课，简直魂都要飞了。”

敏惠端着水果，不等坐下就说：“以前只知道你们那一片穷，原来还有人抢钱？”

“大家都穷，高年级同学也要吃早饭，当然要抢我们了。”罗晨说。

“要是他们只是拿去自己买早饭就好了。”我说，“我亲眼看到他们早上抢了钱，就去糕饼店买蛋糕吃。下午抢的钱呢，就拿着去游戏厅。”

罗晨从敏惠刚放下的盘子里拿起一颗葡萄扔进嘴里，对我妻子说：“所以你老公就动了念头，要去偷饼干，反正糕饼店老板也收过我们的钱。”

我说：“喂喂，你记错了吧，我记得是我告诉你这件事，你才动了歪脑筋，要去夜袭糕饼店。”

罗晨说：“反正这事我们都有份，饼干也是三人平分的。”

我妻子来了兴趣：“你们真的去偷了？”

我摆摆手：“我就是在门口望风的。当时还有谁？六毛是吧？那天半夜，罗晨和六毛叫上我，说去偷饼干。我肚子正饿呢，就跟着去了。他们两个当时比我高半头，就从糕饼店后面的气窗翻进去了，我就绕到店门前面去，马路上一个人也没有。突然糕饼店里面灯就开了，然后一个蒙面人打开门把我拖进去，我差点没吓死。”

罗晨捧腹大笑：“那是饼店的伙计起床干活了，六毛和我怕被认出来，就脱了衣服蒙在脸上。当时也不知道，做糕饼的人原来这么早就要起床。”

我接着说：“你拿着擀面杖，六毛拿着他那把小刀，把伙计按在椅子上。我找了绳子把他捆起来了。六毛还想往他嘴里塞袜子，后来发现我们四个都没穿。”

敏惠和我妻子都好像很有兴致地凑近了一点，听我们讲这个我们自己都记不太清的故事。

“好像那会儿伙计也是刚起来，面都还没有和好。”罗晨说。“六毛就拿刀逼着伙计问，先放什么，再放什么，放多少。我和你就在那儿放面粉，打鸡蛋。我们两个都太饿了，边做边吃。”

“后来伙计说老板就要来了，我们有点着急，就把烤炉的火弄大了一点。结果烤出来的饼干，外面焦了，里面还是面粉砣子。”我拿起敏惠烤的饼干，还是女人在现代化的厨房里，从容不迫地烤的东西好吃。

妻子问：“后来你们被抓到没有？”

罗晨说：“那倒是没有，不过从我们三个的体型，很容易就能想到是旁边学校的中学生了。”

“然后就是全校开大会。校长气得要死。六毛说，糕饼店老板是校长的亲戚。”

“你们男孩，是社会的未来！”那些难吃的饼干的味道我都记不清了，但是还记得那天校长在讲台上歇斯底里地喊的样子。“人穷不能穷志气！你们只有好好上学，以后才有出路！不然就是在这个贫民窟里，先抢人，然后被抢！”

当时六毛坐在我们旁边，还嘟囔了一句：“出路就是开糕饼店，再买个校长当。”我和罗晨拼了命才憋住笑。

罗晨说：“虽然我们当时都穷得叮当响，成绩也不好，不过整个中学阶段，称得上是坏事的，我们也就做过这一件。”

敏惠说：“那样就好。那个六毛后来怎么样了？”

罗晨说：“他后来真是坏事做尽。初三就开始真的抢钱，高一的时候打群架把人打成终身残疾。后来好像在家乡混不下去就出走了。”

妻子也瞪大了眼睛：“后来呢？”

“后来就再没听到他的消息。然后是这个。”罗晨从沙发后面的一堆杂志里找到一本，摊开。通栏大标题是“我的成功没有秘诀——毛六顺谈投资理念”，六毛头发稀疏了不少，手上多了两个大金戒指，眉眼之间的神情，还能看得出当年吃到我们烤的饼干时的得意。

妻子和敏惠都显出有点失望的样子。“你们一定以为六毛死了或者进去了吧。”罗晨说。“人的命运，真是难以预测。”

我玩着车钥匙，问罗晨。“对了，我们那个校长后来怎么样了，你知道吗？”

“后来也发达了，听说是我们这一届升学率很高，很多人找他去讲课、培训。后来他被调到省城去了，听说也是把工读学校生生办成了重点高中，现在应该已经功成名就退休了。说来有趣，他每次都是先办男校，再改成男女混合的学校。不过嘛，他的直男癌是改不了的，即使改成混校，女生也很难进去。每一届都是教委硬给他安排的一批女生，其他女生即使按学区应该上他的学校，都很难报上名。”

“好像真是这样。我们高二那年来的也都是转学生吧。”我说。

“是啊，真想不通怎么高二了还有那么多女生转学，难道附近有女校被关了？”

敏惠善解人意地站起来，拍拍我妻子的手：“我该去准备午饭了，你们继续聊。”

罗晨看了看我妻子，说：“我跟你这么多年哥们儿了，说句不怕得罪嫂子的话，我们虽然从来不是那种好学生，可是逃课谈恋爱这种事，还真是只在高二那年干过。”

我抓起有六毛的那本杂志朝他扔过去：“逃课谈恋爱的就你，可别把我扯进去。”

罗晨说得激动起来：“就算你没逃课吧？上课递字条，还被老师抓起来罚站，这事有没有你？”

“那也是你，叫你递给李心怡就给她呗，你还非要传给吴薇看，生怕别人不知道你俩在好啊？”

我妻子插了一句：“她叫李心怡啊？”

还没等我解释什么，罗晨就看热闹不怕事大地接了茬：“没错没错。我还记得她的模样呢，个头不高，鼻子翘翘的挺好看，喜欢扎马尾辫，我看他俩周末一起出去的时候，她就穿个浅蓝色的蛋糕裙子，蛮可爱的。”说完还朝我挤挤眼。

我和妻子都笑了，罗晨形容的这个女生，分明是他老婆敏惠。

我说：“其实在那个和尚学校里呆了几年，我们也不知道怎么谈恋爱，就是喜欢跟女孩子呆在一起罢了。”

罗晨点头，看看在厨房里忙碌的敏惠：“是啊，其实在一起也就是说学校里那些事，最多也就说说家里的事，爸爸做什么，妈妈是哪里人，之类的。”

“说起来还是你们女生早熟，有城府。”我又拿起一片饼干吃起来。“我记得我当时什么都跟这些女生说，可是她们自己的事情她们就很少说。”

“我猜，都是女校里出来的，无聊的乖乖女吧。”罗晨说。“还好那个时候六毛已经跑路了，不然这些女孩一个个都看不上他，他还不郁闷死。”

“你们篮球都打得挺好的，我下午还得回去帮妈妈扫除，就不去给你们加油了，你们一定能赢！加油噢！”我想起李心怡那次是这样说的。“当时我们这些小男生简直被玩弄于股掌之间呀，被女生放了鸽子，还美得屁颠屁颠的。”我想起那天的球赛，就罗晨他们几个傻大个在球场上挥汗如雨，旁边助威的只有作为替补队员的我。

“长得帅不管用，篮球打得好也不管用。”罗晨继续回忆着。“吴薇有一次跟我说，你知道我为什么只喜欢你吗？我说因为我长得帅呗。吴薇一下子变得可严肃了。她说，不对，是因为你文章写得好，我知道，文章写得好的人，是心灵细腻聪颖的人，我就喜欢你这点。”

“吴薇算是班花吧，她这话一说，我们班男生都下功夫改作文去了。一篇周记，我记得我也改了三遍才敢交，不然只怕要被老师拿出来当反面典型。”我对妻子说。

“你还怕这个，我那时候物理作业都要找好几个同学一起做，对过答案没错了才敢交，都是因为你这个每次都全对的变态。”罗晨说。“来来，喝茶喝茶。”

我说：“我也就原子物理那部分学得好点儿。你知道为什么吗？因为李心怡曾经跟我说过，她喜欢我写完作业以后，把草稿纸撕碎扔掉的样子。她说特别像奥本海默。我还为这特别找了奥本海默的传记看。”

“可惜你也没继续当物理学家，我也没当成作家。”罗晨说。“我们都成了有车子房子妻子的小中产。”

敏惠从厨房里端着菜出来，招呼我们：“吃饭了。”

我和妻子起身，罗晨拍拍我的肩膀：“今天别回去了，我这有瓶好酒，咱们干了它。”

午饭后，妻子和敏惠去收拾，我和罗晨并肩坐在沙发上喝酒，面前还是那本杂志，六毛得意地盯着我们。

“我上大学之后就和吴薇失去联系了。”罗晨晃晃酒杯。“第一个学期，就说她喜欢上她大学同学了。等寒假回去，我连她电话都打不通了。”

我想着自己类似的遭遇，心不在焉地玩着手机。“对了，你用 Arkut 吗？我加你？”

罗晨说：“还是我加你吧。”他按亮手机。“arf dalek，这个是你吗？”

我扭头看看他的手机：“还真是。可能系统看到我们上过同一个学校，地理位置又很近，就自动推荐了。”

妻子和敏惠肩并肩在厨房里洗着碗。罗晨说：“你知道吗，有时候看着这一切，我禁不住会想，要是我当年跟着六毛跑路了，我会拥有这些吗？会像他那样一夜暴富？还是像我爸爸那样，靠给人砌墙过日子？”

我说：“肯定不会像现在这样。要是没有吴薇和李心怡，我们这班男生现在一个个肯定都是穷光蛋。在那种贫民窟里面，像我们这样全都混成中产的，全国也找不出来多少。”我想了想又说：“我有时候觉得，这种生活并不是我们应得的。我们都成了高效的学习机器，这才改变了自己的命运。可是到头来，机器还是机器，我们都不过是一条大流水线上的部件罢了。”

“校长说我们是社会的未来的时候，他不知道有没有想过我们的未来是这样。这么成功，又这么相似。”罗晨说。

罗晨的酒是好酒。不一会儿，妻子和敏惠收拾餐具的动作好像变得机械起来，我不再抗拒，睡着了。



半夜，我又醒来，喉咙有点干。妻子在我身旁，发出均匀的呼吸声。我翻身抱住了她。

“怎么了？”她说，伸手去开台灯。

我捉住她的手，塞回被子里。“我们生个孩子吧？”

“什么？现在？我还在吃着药……”

“我又没说今天就生。”我讪讪地说。

“吓我一跳。你平时都是周末才那啥的。”妻子翻了个身又睡了。

我躺在床上，右边是我的妻子。

我想罗晨在楼上也是一样，头朝北脚朝南，右边是他的妻子。我们是一群相似的学习机器。

“来，抱抱。”我伸手抱住妻子，鼻子在她的头发间嗅着。我似乎闻到了一些陌生的气味。
