#+TITLE: Embodiment: 过时的观念？应验的预测？

上世纪90年代，计算机拥有了基本达到实用水平的图形用户界面，与此同时，World Wide Web 的出现推动了 Internet 从少数人的工具向大众的工具、传媒和娱乐的转变。这二者使得计算机和网络第一次有可能摆脱技术的界限而进入文化的范畴。Cyberpunk/cyborg 作品和虚拟现实技术的推广对这一趋势起到了推波助澜的作用。社会学研究者自然不会放过这一新兴的文化现象。这是 “Cyberspace/Cyberbodies/Cyberpunk”这本书写成前后的社会背景。

与人类发明的其他工具相比，计算机和网络的独特之处就在于其提供的“空间”允许新的实体、新的关系存在，从而使新的文化成为可能，同时也对基于传统关系的空间定义提出了挑战。在这个新的空间与社会这个传统空间的交叠部分——也就是普通人能与其发生作用的界面，现实、人、智能等等定义都可能需要改写。对“现实”的体验，对自我人类身份的认同，以及基于计算机和网络的文化在社会中产生的深层意义，是这个时代的许多人都可能感兴趣的问题。

Cyberspace/Cyberbodies/Cyberpunk 便试图从 VR（Cyberspace），cyborg（Cyberbodies），以及关心记忆、身体和认同的 Cyberpunk 文化三方面入手讨论计算机和网络对人的异化和冲击。其中 Cyberbodies 这个概念是全书的核心，对另外两个方面的探讨都不能避开它们对 Cyberbodies 的影响。这也许是本书副题的由来：关键是讨论人类与自身发明的技术的融合。而对于 Cyberbodies，记忆、智能、身体和认同都在这个融合的过程中产生了含义的转变。其结果是这样的问题：我们如何改变自己才能在新的世纪中存活？经历了某些改变之后的个体是否还能被称为人类？或者，拥有能改变自身记忆和身体的能力的人，如何确认自己是一个一般意义上的人类？

这本书的作者们利用哲学和社会学的批评方法对这些问题进行了讨论，其中不乏精彩的论述，特别是 A. Landsberg 对记忆的分析和 V. Sobchack 关于身体的思考。遗憾的是作者当中似乎缺少一个真正意义上的 Cyberpunk，这固然保证了书本的客观性，但不免让人觉得有指手划脚之嫌。

由于成书的年代比较早，今天的读者会发现书里讨论的某些问题，现在已经不被看作问题；某些讨论到的文化现象也早已淡出了我们的视野。比如虚拟现实技术始终都没有达到作者们设想的全浸入式设备大量应用的程度，但在大众话语中已经不太被提起了，又比如 cyborg 的概念在流行文化中已经不是主流（2008年初，从北美电影题材看，流行文化是 slasher，恐怖分子，漫画英雄和平凡人，立此存照）。那么 technological embodiment 的讨论是否还有必要？

首先可以明确的是今天的 Cyberspace 是以更加外化的形式存在的。虽然书中预言了众多“人”可以在其中生存的电子空间，现在的 MMORPG 和 Second Life 之类人造环境也确实可以做到让人流连忘返，但它们并没有影响到其用户对自己的认同。虚拟现实和机电技术导致的人类作为个体的异化表现得并不明显，而网络带来了独立于个体的一种新的存在形式，其本身并不能看作人的异化。但另一方面，不可否认的是技术改变了相当一部分人的生活方式。比如对 NYSE 的一个交易员来说，他使用计算机和网络进行交易的方式完全不同于其先辈作为一个“自然”人所使用的方式，而他如果不使用计算机和网络就无法完成他的这项工作，那么是否可以认为计算机和网络决定了他的技能、身份和他人对他的认知呢？人类与技术在身体上的融合也许只能是很久以后的事情，但在智力活动层面上的融合却是从未中断过的。Embodiment 的讨论当然还有必要，但这本书作为先行者的使命恐怕即将结束，未来对于 embodiment 的探讨似乎要从更加抽象、更加宏观的角度着手了。
