#+TITLE: 当穿靴猫变成101忠狗

Dreamworks Animations （DWA）与 Pixar 的关系就有如 AMD 和 Intel。后者主宰了主流消费者的口味，也是前者模仿的对象。正如 AMD 最具划时代意义的产品是首先实现64位运算和寻址的 Athlon，DWA 给人印象最深刻的形象也是离经叛道，恶搞了大量经典童话的 Shrek。How to Train Your Dragon 想要证明 Dreamworks 不仅能用 Shrek 这样的形象颠覆和剑走偏锋，也能驾驭中规中矩的家庭动画长片。但是，这样的证明不应当用落入 Disney 曾经的俗套为代价。

How to Train Your Dragon 的主角和剧情很像 Pixar 早年的作品 A Bug’s Life，但是 Flik 走过的旅程要显得比 Hiccup 的成长经历可信得多。相比 A Bug’s Life 里那些连本职工作都常出差错的虫子，Hiccup 的搭档是一条威力无穷的，“Never misses” 的传奇飞龙，如此强大的存在无疑使主角的发挥空间少了很多。虽然主创人员希望把 Hiccup 描绘成一个能力有限但充满斗志的形象，从而拉近与观众的距离，但他的搭档的强大只会让观众想到传统童话里捡到神灯的阿拉丁，或者从悬崖上掉下去都能捡到武功秘笈的张无忌。而 Hiccup 无法复制 Aladdin 或者《倚天屠龙记》的成功，则是因为笔墨被过多地用来塑造 Toothless 的形象，甚至众多种类不同的龙的形象，而只塑造了一个平面化的主角。观众也许会记得傲娇的 Astrid，甚至长得有点像 Jack Black 的 Snotlout，但是不会对 Hiccup 有太特别的印象，顶多一边想“为什么我捡不到龙”一边出戏罢了。

即使现在以 Pixar 为主力的 Disney，也不会使用这样一个平铺直叙的剧本。很难认定平面的主角和平板的剧情孰为因果。在一般的编剧公式中，主角总要受到重大挫折，被别人和自我怀疑和否定，最终方得正果。这个自有戏剧以来屡试不爽的公式存在至今，自然是因为它符合观众的心理。在 How to Train Your Dragon 里，情绪始终在一个温吞吞的温度徘徊，最后虽然燃了一下，但是因为与之前的情节缺乏对比，效果也不出彩。主创虽然试图用人和龙之间的紧张关系制造冲突，但 Hiccup 的成长过程一帆风顺，人和龙的对峙就缺少了具体的表现形式和镜头中的落脚点，让观众难以设身处地去体会。影片传达的呼唤沟通和消除误解的信息，在今天具有强烈的现实意义，但是如此宏大的主题，没有一个令人信服的主角和搭档关系来具象化，是很难被观众打心底里接受的。

男女主角遨游云海的场面和与 Pocahontas 一样的主题思想，在无力的剧情之上就成了对 Disney 俗套模式的笨拙模仿。

虽然 How to Train Your Dragon 的缺点让它像是一部适合直接转 DVD 的小格局电影，但如果不在影院里欣赏这部片子，那些缺点还会更突出一些。至少，每一个男观众都能借助影片中不输给 Avatar 的飞行场面温习少年时代的梦想，而 DWA 花大力气塑造的龙也确实像我们的宠物猫狗一样可爱。

如果不是影片的结尾，我宁愿相信这是 Disney 旗下另一个工作室用来练手，直接走 DVD 发行渠道的作品。但是当不完美的主角和不完美的龙完美地结合在一起的时候，我相信这才是 DWA 和原书作者 Cressida Cowell 想要描绘的人与龙的关系。也只有这样的结尾，才像是一部真正的 DWA 电影。我希望看到的，不是作为 Pixar 模仿者的 DWA，不是走101忠狗路线的穿靴猫，而是像 Shrek 一样叛逆和像 Kung Fu Panda 一样给人惊喜的梦工厂，而这个结尾给了我期待的理由。
