#+TITLE: 生态/环境研究的新挑战

Holling (1973)[1] 这样定义生态系统的 resilience：系统在发生重构和功能变化之前能够接受的最大扰动。而 Pimm (1984)[2] 在十年之后才提出 resilience 的另一个定义：系统受到扰动后回到初始状态所需的时间。虽然 Pimm 的定义提出较晚，但却得到了广泛得多的应用。而对于 Holling 的定义，虽然研究者往往会提及，却很少有人将其应用到实际研究中，以致到现在这个概念的研究者和实践者似乎已经成了一个不为人注意的学派。为什么 Holling 的想法应者如此寥寥？

Resilience and the Behavior of Large-Scale Systems（以下 RBLSS）这本书可以看作是这个久被忽视的学派争取学界注意的又一次努力，书中文章的主要作者包括 L. H. Gunderson，C. S. Holling，G. D. Peterson，B. H. Walker，S. R. Carpenter 和 D. Ludwig 等人，事实上他们就是仅有的几位我们通过一般的期刊搜索能比较容易地找到的，主张利用 Holling 的 resilience 定义研究社会-生态复合系统的学者。在书中他们重申了自己的想法，即 Pimm 的 resilience 的前提是不成立的，复杂系统并没有一个唯一、恒定、稳固的均衡（equilibrium）状态，相反系统可能有多个均衡状态，外力可以导致系统在这些状态间转换。在一个均衡状态附近（称为均衡域或吸引域），系统的变化是连续而接近线性的，可以用方程描述，但一旦变化超过了一定范围，系统的转变就是突然、非线性的。定义或者评价一个系统的 resilience，就是要找出均衡域的范围和其它可能的均衡状态。

这样的说法比较抽象，所以 Holling 的追随者们使用盆中的小球这个概念来说明：小球相当于系统，放在一个盆（均衡域）当中，盆的宽度就是 resilience 的强弱程度，而小球一旦越出盆沿，就会落入另一个盆，即一个性质、结构、功能都可能完全不同的系统状态。在数学上，他们则利用二分点这个概念来说明系统是如何离开均衡域的：类似我们熟悉的量变引起质变的思想，系统某些变量的取值会使类似下面方程的性质在这个取值附近发生巨大的改变：

$$\frac{dx}{dt} = -x(x^{2} - \alpha)$$

这类变量称为系统中的“慢变量”，变化往往较慢，却对系统的性质和功能有根本性的影响。到这里我们已经可以看到 Holling 的定义固然比 Pimm 的定义更能把握生态系统的非均衡本质，同时也避免了过度的还原论思想，但其实践比起 Pimm 的仅仅通过经验性的观察就可以测量的方法要困难许多，要求研究者对于系统的全面性质和各种内外影响因素都有较全面的了解，这在大的生态和社会经济系统中是难以做到的，难怪许多人望而却步。

也许正是因为这一点，RBLSS 这本脱胎于 workshop 的书将重点放在对大型系统的具体案例研究上。其研究的系统包括了主要的陆地生态系统如森林、湿地和草原，以及水生生态系统如湖泊和珊瑚礁群，研究方法也是多种多样，包括情境分析，数学建模，实地观测和地理信息科学等等。这些案例确实体现了 resilience 这个概念的普适性，但也暴露了它的一个重大不足，就是对于不同的生态系统缺乏一个一致的方法体系。即使在同类的生态系统中，由于物种和扰动因素的不同，研究者也往往不能套用书中给出的分析结果，而要自己从概念模型开始分析。在整个体系中缺乏“可重用”的部分，无疑也限制了这一概念像环境影响评价那样成为工业和学界中通行的做法。

当然，仅从框架来说，这本书也提供了一个可供套用的模式，包括概念模型的建立，跨比例过程和慢变量的识别等等，可供有意利用这个概念进行研究的人参考。但我认为这本书更大的意义在于指出了一条有可能让生态学研究从目前的还原主义研究方法飞跃到真正综合性的，把“人”这一因素纳入研究范围的研究的途径，向传统的研究方法提出了挑战。同时，相对于基于 Pimm 概念的，以某一特定状态为目标、要求保持和固守的环境管理，Holling 的 resilience 概念使得他能够提出新的生态/环境管理思想，即适应性的管理，承认生态和社会系统的变化和非均衡性，这比 resilience 这个概念本身有更大的实践意义，已经在一些具体的环境管理方案中得到应用。在 resilience 的评估当中，又要求研究者对现有的生态模型进行检验，并研究和归纳具体生态系统当中的各种主体和相互作用，这在一定程度上也促进了传统生态学理论和方法论的发展。从这个意义上说，这本书和 resilience 概念本身，对于生态和环境科学的研究者来说具有超越直接价值的意义。

[1]Holling, C. S. Resilience and stability of ecological systems. Annual Review of Ecology and Systematics, 4:1–23, 1973. 
[2]Pimm, S. L. The complexity and stability of ecosystems. Nature, 307:321–326, 1984.
