#+TITLE: “注意力经济”可以解释更多的事情
#+AUTHOR: Haoyang Xu 

Scarcity / Sendhil Mullainathan & Eldar Shafir / Macmillan, 2014.

和很多畅销作品一样，这本书试图用一个简单的理念——资源的稀缺造成使人深陷其中的陷阱——来解释一系列我们习以为常的现象。这些现象包括总是到最后关头才努力工作的成功人士，债台高筑的农民和普通工人，以及无法缓解的贫困。造成这些难以跳出的陷阱的，不是当事人的懒惰和缺乏自制力，而是时间和金钱的稀缺天然地就会造成这些稀缺的延续。

作者认为可以用一个统一的模式来解释这些现象：稀缺造成注意力集中于正在体验稀缺的事物，当没有钱用时，你自然地集中考虑如何减少开支，当没有足够的时间时，你自然地把精力用于最迫切的任务。而注意力的集中导致所谓的隧道视觉，那些能够帮助人们在长期摆脱稀缺的机会，因为这种集中，被挡在隧道之外，这样到下次，稀缺的资源仍然稀缺，迫使人们继续按照过去的做法行事。

点破之后，这似乎是个浅显得不言自明的道理。但作者由此引申，认为破解时间不够用、钱不够花，乃至扶贫计划总是失败的一个办法，并非过去人们设想的硬碰硬提高个人纪律性，或者加大投入，而是在资源的配给中提供更多的余量，将个体决策者的认知带宽作为一种资源保护起来，以便它们用剩余的带宽考虑长期的解决稀缺的办法。这就是一种新的思路了。

基于这个思路，作者在最后一章试图为前面提到的各种说明稀缺导致的注意力缺乏和陷阱提供解决方案。例如怎样解决工人总是用高利贷方式预支工资，导致负债累累最终破产？雇主应当提供更灵活的工资支取方式和更有效的金融手段。

作者没有明言的是这本书里讨论的稀缺现象都与某种周期性的过程有关。稀缺陷阱难以跳脱正是因为每个周期都带来本质类似而程度不同的挑战，占据个人的注意力。因此解决稀缺的要点并不是简单地提供更多的资源，因为分配不当的资源只会因为暂时的充裕而被排除在思考过程之外，当它们再度变得稀缺才会进入人们的视野。这种突然增加的资源甚至可能延缓问题的出现，而当问题出现时，它们变得更严重甚至不可收拾。保护认知带宽的要点似乎在于计划好资源的供给和使用之间的平衡，使严重的稀缺不至于出现，从而使人们始终有认知上的余裕来考虑如何在长期保障资源的供给。很多情况下，人为地缩短周期的长度，能够使得资源的供给在整个时间段上显得更加平均，从而使人们能够对各种长期和短期的需求保持较为平衡的关注。

换句话说，要解决拖延和抱佛脚的时间稀缺问题，或者举债和贫困的金融稀缺问题，社会管理者应当提供的激励不是更多的时间或者金钱，而是较短的资源补充周期和与之对应的较轻的个人责任和更容易具象化的目标。此外，一些制度的小设计，也可以减少人们的认知负担，在不占用带宽的情况下就能采取避免稀缺陷阱的行动。
