#+TITLE: Way to go Cpt. Kirk

上次看 Star Trek 电影还是上世纪九十年代看的某国内电视台盗播的 Star Trek VI: The Undiscovered Country，从那时到今年我没有看过这个题材的任何真人实拍影视作品，所以我相信我写的这些还是比较能代表大部分普通人的口味的。从一个比较正常（相对 Trekkies 来说）的科幻片影迷的角度讲，J. J. Abrams 的这部新 Star Trek 完全满足了它的预告片和 Rotten Tomatoes 上 95% 的好评率带给我的期望。

从影片的剧情安排，不难看出导演的意图是一方面调动 Star Trek 系列本已存在的数量庞大的 trekkies/ers 群体，一方面重新启动这个在过去近二十年中几乎已被遗忘的系列，让新影迷认识 Star Trek 的魅力。我相信 J. J. 至少很好地实现了前一个目标。虽然影片剑走偏锋地没有加入 Klingon 的戏份，但无论是剧情还是场面，都忠实地还原了 Star Trek 系列激烈、紧凑的风格，而且在视觉效果方面更上层楼。任何接触过 Star Trek 的人，看到新世纪电影技术打造的 NCC-1701 企业号（奋进号？），都必然产生见到老朋友的感动之情。

至于吸引新观众方面，因为我已经受过 Star Trek 的“毒害”，不好妄下断言。但可以肯定的是，Star Trek 在这一点上将比 Star Wars 系列要成功，因为这个剧本基本没有预设观众看过以前的影片/电视剧，而且将其从系列中独立出来看，即不考虑 Star Trek 名气的影响，它也是一部很有亮点和发展潜力的新作。在短短两个小时的时间里，Star Trek 交代了系列的世界观，讲述了一个完整的故事，同时塑造了一群鲜明的形象。有了这些要素，我想不论新老 Trek 影迷都已经可以期待一个成功的续集了。把一个长期被边缘化的系列重新塑造成好莱坞的一线题材，将是这一部 Star Trek 可以在系列历史上夸耀的功绩。

当然，要同时满足老一代 Trekkie/er 的怀旧要求和新一代观众的口味并不容易，Star Trek 也需要做一些妥协。剧情方面为了照顾新影迷，不能过多地涉及作为系列背景的政治、历史要素，（再次抱怨一下）连 Klingon 也没有正式出场；而为让老一代 Star Trek 演员出场而安排的一段戏也略显突兀。不过剧情还是保持了 Star Trek 一直以来吸引观众的要素，在近年来的科幻题材影片中，体现了很高的编剧水平。特别是剧本能把改变历史/平行宇宙这样的题材说圆了，是非常难得的。

影片启用了大量的年轻演员，可见制片方看到了这个题材的潜力，很可能将其作为一个长期发展的系列。虽然在影片拍摄期间有人怀疑如此年轻的演员能否演出当年 William Shatner 和 Leonard Lemoy 的那种魄力，但看到这些演员的表现后他们的疑虑应该可以打消了。他们也许演不出老演员的那种沉稳，但他们也演出了年轻的企业号船员的果断、勇敢，以及作为系列标志之一的冒险精神，这是年龄稍大的演员很难演出来的效果。要注意的是根据剧情，他们还都是未出茅庐的军校生。有些表演看起来有些像校园剧，但只要这些演员比他们的角色成熟得快，在下一部 Star Trek 里这应该就不成为问题了。

影片在紧张中不失幽默，虽然暂时还没有体现出任何深邃的内涵，但足以让观众被这个系列所吸引，并在希望回顾系列以往作品的同时期待新作的到来。建议携三五好友一起到影院观看，以获得最佳观影体验，银幕越大越好。当然如果你的朋友或者男（女）朋友对科幻题材完全没有兴趣，还是三思而后行……

另外还有句题外话。最近看上世纪70年代拍摄的 Battlestar Galactica 旧系列，注意到里面的飞船还在用球面的 CRT 单显做显示设备，战机使用的是机械式的水平仪，不由哑然失笑。2009年的企业号已经用上了多点触摸设备，或许再过30年，也会被那时的观众笑话？更重要的是，许多年以后现在的科幻片新题材有没有哪一个能够像 Star Trek，Battlestar Galactica，Terminator 和 Transformers 一样继续拥有广泛的影响和焕发新的生命力呢？也许是 Lost 和 Cloverfield？Way to go Captain Kirk, way to go J. J.!
