#+TITLE: What we talk about when we talk about love
#+AUTHOR: Haoyang Xu
#+DATE: 2016-03-23
  
I have once read Carver's /Cathedral/, which is a later collection of stories, written after Carver was better off. It was very good, except that I find the language softer, and more decorated, compared to this 1981 collection. Perhaps Carver's life did change in between these two books. The coarseness texture of /What we talk about .../ gives the book unique charm: you are concerning the character's fate even when you are fully aware that they are just virtual personalities. 

Many find Carver's book hard to grasp, which I think is because they are trying to put too much meaning into it. Carver exposed shitty lives that he knows very well to us, and had done a very good job. His brilliance is in that we may be unfamiliar with that kind of life, and try our best to avoid it. But we identify with his characters. He achieves much by using very few words, not only describing a scene, but also hinting all the conflicts behind people's interactions. Maybe he did know what to include and what not to, and that is gold for a story teller.

Carver himself acknowledges this in [[https://sun.iwu.edu/~jplath/carver.html][an interview]], he said:

#+BEGIN_QUOTE
In my second book, What We Talk About When We Talk About Love, the stories were very clipped, very short, very compressed, without much emotion. In my latest book, Cathedral, the stories have more range. They're fuller, stronger, more developed, and more hopeful.

...

No, not intentionally. I don't have any program, but the circumstances of my life have changed. I've stopped drinking, and maybe I'm more hopeful now that I'm older. I don't know, but I think it's important that a writer change, that there be a natural development, and not a decision. So when I finish a book, I don't write anything for six months, except a little poetry or an essay.
#+END_QUOTE

It is possible that Carver's writing style is due to the fact that he did not conciously learn from any writer, especially those highly praised by America's literature tradition. Carver came from the lower class, and he wrote for them. Description of character's mental status and silent monologues are used by many authors, such as Philip Roth and Jonathan Franzen, and are quite popular among the academics, but Carver wouldn't use it, as the working class don't like it, or are unable to appreciate it.
