#+TITLE: 全球化与经济地理学

关于全球化如何定义及怎样看待，在地理学和经济学中都有众多的定义，众说纷纭而莫衷一是。全球化的推动者们认为全球化的图景就是一个完全竞争、国界消失的全球经济，而且这一图景的到来不可避免；全球化的反对者则认为全球化带来的是身份认同和选择的消失。但事实上，这些对全球化的阐释并没有忠实地反映当前被人们认知为“全球化”的现象。在今天的全球化中，充分的竞争由于掌握大量体制和经济资源的跨国公司的存在而不能实现，而跨国公司为了占领本地市场，也必须强调其产品和服务随当地文化而变通的灵活性，民族身份认同不是被取消，而是得到了加强。

如何看待这样的全球化及其成因决定了我们将如何适应和推动/阻止全球化。Herod 首先从地理学的角度，提出经济（Economy）是一个空间过程，而不同于传统经济学使用的仅考虑劳动、薪酬和租金成本与收入的立即交换的模型。通过承认经济是一个空间过程，读者可以开始理解通讯和运输技术给产品和服务的交换带来的改变，即地理如何影响资本主义经济以及相关的社会结构，更重要的是，经济的社会构建如何影响社会的地理关系。经济因此是一个受空间关系影响的、动态的社会产物。

这是理解本书需要掌握的关键结论。在第一章提出这个观点后，作者开始从全球化的视野、阐释和叙事的角度来阐释全球化这一概念的形成过程。作者指出，西方的地理大发现，以及随之而来的远洋航行和殖民史决定了西方国家在制订全球的空间（北向上的地图）以及时间（国际日期变更线）方面的主导作用。这些优势是商业发达的西方获得的先发优势，但据此认为一个统一的全球市场是全球经济唯一的未来是武断的。首先，技术的进步并不能说明全球化的不可避免，可以看作推动了全球化进程的事件在我们熟知的许多技术发明之前就已存在；其次，全球化也不是一个步调统一的过程，认为统一的全球市场必然出现是忽视了空间差异性的结果。这部分的论证是书中的第2--4章。

第4章之后，Herod 又各用一章的篇幅，讨论了殖民时代的地理遗产对形成新经济关系的作用，制造业和 FDI 与全球化，民族国家与全球化，以及劳工和劳工组织的全球化。但以我之见，这几章鲜明的历史色彩表明了它们的真正作用还是作为第4章提出的“全球化并不新鲜”这个观点的注脚。Herod 在这几章里想要说明的观点，是我们在今天的全球化中观察到的现象，有的并不像人们想象的那样减少了民族国家的控制，或者只是一个更大的历史周期的一部分。因此那些认为全球化不可避免的观点是站不住脚的。全球这个尺度，乃至于全球化本身，都是人们在经济研究和社会生活中人为建构的概念。

作者的根本目的，在于批评新自由主义对全球化的构建。不可否认，即使是左派的反对全球化的人群，有时也不免落入新自由主义叙事的窠臼，反对的是新自由主义看作是不可避免的未来的那个全球化。Herod 要提醒读者的是，新的物质流动过程在以新的方式把这个世界联系在一起，而我们如何看待这个新过程，取决于我们采用什么样的历史和地理观，以及怎样划分人类历史的各阶段。更重要的是，读者要认识到全球化的主流叙事来自于信息发达的北方世界，学会辨别新自由主义的全球化观念，并理解这种地理学对于世界经济关系的构建的作用，才能正确理解新的经济过程和这个过程中全球公正的实现。
