#+TITLE: 切过复杂性的乱麻
#+AUTHOR: Haoyang Xu

The Watchman's Rattle: Thinking our way out of Extinction / Rebecca D. Costa / Vanguard Press, 2010.

在进化史上，人类的特殊之处可能是：它是第一个有能力大规模地改变环境的物种，从而也是第一个面临自己制造的环境带来的选择压力的物种。

这种压力体现为我们的生存和生活必须面对各种复杂性。复杂性意味着我们无法确定地了解我们所采取行动的后果，也无法通过单一的方式解决涉及政治经济社会复合体的种种顽疾。在复杂性带来的压力面前，有的社会满足于临时的缓解办法，有的社会陷入迷信，这些做法都导致社会最终陷入僵化，甚至放弃本可用来解决问题的资源，并在问题大得无法收拾时陷入不可逆转的危机，最终崩溃。

尽管历史上无数的文明都因为无法管理这种复杂性而灰飞烟灭，成为前车之鉴，但人类的天性和文明发展的程度都意味着复杂性的增加不可避免。每个人都能在试图选择商品，制定旅行计划和设计职业规划时体会到复杂性带来的困难，而对团体和国家来说，复杂性时刻挑战着它们的组织机构和知识，做出好的决策变得难上加难。

面对复杂问题，人们不能有效应对的原因之一是一些“超级迷母”的存在。这些超级迷母不仅能够很快地在人群中复制自身，而且能排挤其他的迷母，使创造性的解决方案难以出现。书中点名提到了5个超级迷母，包括自动的反对立场，对个体的指责，对相关性的过度解读，部门化的知识和经验，以及商业化的单一价值观。这些迷母阻碍了人们对信息的认知和思考，因此是解决复杂问题所必须先克服的障碍。

根本的解决复杂性问题的方法在于使用不同于左脑或右脑思维的第三种思维，书中称其为“洞见”（Insight）。洞见类似于我们文化中的“灵机一动”或“急中生智”的现象，基本上可以认为是一种直接针对问题本质，简洁优雅的解决方式。洞见是可遇而不可求的，但通过对自身思维习惯、对组织架构和对信息获取方式的转变，我们可以促成洞见的出现。

此书的阅读使我不断在击节赞叹和摇头叹气之间摇摆。我欣赏作者对这个高度复杂问题的关注，人们致力于榨干芯片的性能，或者雕琢软件的细节，所谓的工匠精神受到推崇。相比之下，人们对数百年内我们可能遇到的问题并没有给予足够的关注。从大学里教授的技能到科研资金的分配，都不鼓励跳出常规的思维和新科学的发展，人类的思考模式越来越内化和短期。因为生活已经足够舒适，我们越来越不愿意冒登月工程这样的巨大风险。Elon Musk 可能比 Steve Jobs 和 Jeff Bezos 更值得尊敬，因为至少他还在把眼光投向大气层以外，后两位只是专注于更好的产品，更完善的技术，和更方便的生活而已。但当颠覆性的变化突然发生，原有的让你的生活更方便的技术几乎肯定不会有一点用处。Interstellar 最打动我的一点，也是它试图提醒我们激动人心的科学发现越来越少，而这可能直接影响我们的生存能力。
但支撑激动人心的论点的，是相对孱弱的论据。作者举的几个洞见的例子，比如地质工程应对气候变化，不是很有说服力。而对“脑锻炼”方法的极度热情似乎也没有坚实的研究和数据来支撑。这使人不能不怀疑作者是否也在复杂问题面前采取了用信念代替知识的做法。但书中提出的问题确实是值得思考的，而其提供的解决方式也是相当可操作的。
