#+TITLE: 反躬自省的深度和广度

对“深海地平线”事件的新闻报道呈现出一种杂乱无章的面貌。对非石油专业的人来说，了解整个事件的前因后果非常困难。如此重大的漏油事故，竟然在发生的当天只有少数几家报纸做了篇幅不长的报道，而在事故发生后一个月又成了新闻界的热点话题，延续数月，直到漏油点被关闭才渐渐从媒体报道中淡出，考虑到事发当时其他新闻的平淡，这可算是一件罕事。但在普通大众心目中，钻井平台事故好像是必然发生的迟早之事，石油工程公司也必然最终能控制住泄漏，所以事件刚发生时，还不如美军在阿富汗的伤亡那样吸引眼球，只是到了泄漏愈演愈烈，几乎不可收拾时，大众才重新开始关注此事，这倒也是一般人对新闻事件的典型关注模式。

所幸事故调查委员会出版的这本调查报告 Deep Water: The Gulf Oil Disaster and the Future of Offshore Drilling 不仅再现了事故和应对过程的全貌，还探究了事件背后埋藏于产业界的实践和政府部门的监管制度中的深层次原因。

我们常说，前事不忘，后事之师。前事之不忘，前提是忠实地复述事件的起因经过结果。以一般事故调查报告的思路，《Deep Water》如能做到完整地重述事故是为何及如何发生，便已算是把“前事”叙述清楚。报告第一章，已通过事故亲历者的口述证言，完整再现了事发当天的情形，后面的章节也探讨了事故发生的技术原因。以此为出发点，已经可以就如何在现有政策框架下改进制度和钻井技术，避免此类事故再度发生展开足够深入的讨论，也可算对得起事故调查委员会成立时的目标之一，即想法避免石油开采过程中的事故。

然而，也许是在调查过程中 BP、Halliburton 和 Transocean 糟糕的安全记录引起了报告编写者的警觉，也许是对 MMS 和其他机构的比较研究带来了更深入的思考，报告没有把目光限于事故的技术层面，没有简单地将事故原因归于技术的不完备和工人的疏忽，而是在回顾了墨西哥湾地区石油开采的历史之后指出，数十年来僵化而远远落后于技术发展的政策制定和管理体系，“多龙治水”式的混乱的权力布局，也包括石油产业界在缺乏有效监管的情况下对风险的漠视，才是造成事故的根本原因。事故的责任人已有认定，赔偿过程也正在进行，与事故直接有关的政府监管部门已告解散。报告如此探究美国石油开发制度的缺陷，自然也并不是要指责政府的不力或者商人的无良，而是在观察到过去无数次头痛医头，脚痛医脚式的石油事故处理过程后的痛定思痛。

报告提出的改正措施，同样不限于就事论事地改进钻井安全技术和控制石油污染的办法，甚至不限于对事故的根本原因——低效率的管理制度进行革新，而是将考虑的范围和深度进一步扩大。在减少石油污染带来的生态破坏方面，报告以整体论的观点，建议增强沿海生态系统的恢复力；在降低石油泄露的风险方面，报告一方面注意到阿拉斯加海上石油开采的特殊条件带来的问题，提出预防性的建议，另一方面反思了美国对石油资源的依赖，建议逐步转向可持续能源。或许报告的作者们本来就有利用此次机会影响美国能源方针的意图，但对一次事故的调查报告可以上升到影响国家战略的层面，也让我们看到调查报告应该起到的作用和达到的高度。

这种报告的写作风格，应是起源于2004年的9/11事件调查报告。现在回头去看那份报告，和《Deep Water》比较，其语言风格相差不大，但对于事件的起因和美国应采取的措施的分析，911报告似乎要稍逊于《Deep Water》一筹。一份好的调查报告不仅应该是对一次事件的总结，更应该是对事件起因和将来采取的策略的反思和批评，如此前事才能成为后事之师。《Deep Water》达到的水准，可算是体现了报告这种文体在过去7年中的变革和进步。

在中文语境中，“报告”给人的感觉是事件的记录，个人的体会，责任的划分，仅此而已。然而英文的 report 不是 log 也不是 narrative，也不是这二者的简单结合。报告应有一种态度，以及单个和集体的事件记录所不能体现的思想深度和广度，如此才能起到报告的“资治”作用。
