#+TITLE: 人人都爱灰太郎

国产动画电影经过了自《大闹天宫》之后几十年的沉寂，以及自《宝莲灯》后近十年的不温不火，终于在2009年制造出了一个票房现象和一个真正让不同年龄段的观众都认可的动画形象——灰太狼。小朋友们在每天播放动画片的时段不再是因为没有其他动画片可看而例行公事地为了佐餐而看这个刀疤脸小灰狼在电视里上蹿下跳，而是哭着闹着要看灰太狼，没有灰太狼就不吃饭；以往为了哄孩子吃饭不得不陪着孩子看动画片，陪着孩子为那些自己不太明白的笑话发笑的父亲母亲们，似乎也第一次自觉自愿地欣赏起了这个“给小孩子看的”动画。

如果让70后或者80后的观众回忆小时候看过的国产动画片，再与《喜羊羊与灰太狼之虎虎生威》比较，他们不难得出这样的结论：灰太狼是个非同一般的主角，即使他的出身不好，来自于从“狼来了”到现代一直演反派的大灰狼家族；即使他相比喜羊羊总是呆傻莽撞不知天高地厚；即使他从来不知道谦虚使人进步骄傲使狼落后；即使他从来没有想过要洗心革面做个驯服的狗狗，他的号召力却俨然已经大大超过了机智勇敢的黑猫警长和善良孝顺的葫芦娃。更不用说一个“狼要吃羊”这样一个典型的反派剧情，竟然让灰太狼在小朋友和他们的父母之中的人气指数直线上升，真是让同样一心想吃掉主角蓝精灵的格格巫和阿兹猫情何以堪，泪流满面。总之，人人都爱灰太狼。

虽然喜羊羊与灰太狼的角色设置模式早已有先例（《猫和老鼠》），但灰太狼们在国产动画中仍可算是剑走偏锋，独树一帜。这一群活宝的出现，对于看腻了动画版三大名著和动画版五讲四美三热爱的小观众们，和认定国产动画都是针对小孩子的说教的青年观众来说，都是个惊喜。终于有人意识到，我们拍动画片不是为了把我们永远也无法实现的成为道德完人的希望寄托在孩子身上，而是为了让他们有一个快乐的童年，有一个浑身都是缺点但也浑身都看得到优点的角色陪伴他们的健康成长。而且，作为一部部分观众是儿童的动画片，喜羊羊和灰太狼的教化作用并不因为角色的不完美而被削弱，对于孩子们来说，要向坦率有责任心的灰太狼学习把蛋带回家给爸爸妈妈一起吃，比向浑身上下几乎毫无缺点，只有一个肚脐眼的哪吒学习闹海打龙要容易得多。而作为孩子们第一个榜样的父母，要向喜羊羊或者灰太狼看齐，想必也要比向孟母或者岳母看齐要轻松得多，不容易让孩子失落于动画与现实间的落差。

其实，不仅《虎虎生威》的观众在向灰太狼看齐，灰太狼也在向我们看齐。那个时而自信满满时而垂头丧气的灰太狼，那个要为生计奔忙还要被红太狼用平底锅拍的灰太狼，都像极了生活中的我，你，他。而那两个照章办事，慢条斯理的神像，也真像极了我们这儿内里热心外表爱搭不理的居委会阿姨。戏里的灰太狼这次还是没有抓到一只羊，不过和红太狼喜羊羊一起克服了生活中最大的危机，继续在自己的小家中过着幸福的生活；戏外的我们也盼望着能在打拼了一年之后，全家一起看看《虎虎生威》，热热闹闹地迎接虎年。虽然歌词有云，做人要做喜羊羊，但其实，人人都是灰太狼，不那么乖巧，不那么机智，充满了缺点，有更多的优点，偶尔还会优点爆发一下力挽狂澜，挺好。至于孩子们，但愿他们永远都是无忧无虑的小灰灰。
