#+TITLE: 维持风格，打破定律

好莱坞的一般影片，如果制作方仅仅是因为第一集大卖而决定拍摄续集，续集的质量就往往不如前作，除了 Terminator 2，The Empire Strikes Back 和 Godfather 2 这样的例外，续集比第一集成功的寥寥无几，甚至可以说大部分续集比第一集的水准相差甚远。但在漫画改编电影中，第二集比第一集成功似乎倒是一个普遍现象，从较早的 Superman 2，到新世纪的 Spider Man 2 和 The Dark Knight 都表现出了比第一集更高的品质。

非改编电影的续集受到这样一些制约：影片主题可能在第一集里已经做了深入的探讨，导致续集只好选择狗尾续貂或者另起炉灶；编剧的点子在第一集里已经用完，在续集里很难继续构建有力的戏剧冲突，容易落入俗套；第一集里对故事的背景、人物的性格刻划都已经形成了固定的框架，导致续集的编写不得不继续带着更多的镣铐跳舞。漫画改编电影因为第一集的试水色彩往往更重，以把多年不看漫画的观众拉进影院作为主要目的，第一集拍得都比较中规中矩，到了第二集，因为有上一集收入的资金作为后盾，编剧人员就可以像《纽约时报》的影评人 Scott 说的那样，冒险探索“那些肤浅幼稚的故事里的诡秘角落”，给人物更多的深度和更强烈的冲突，而且有漫画上百期连载的底子，找几个符合编剧意图的故事和角色加以改编也不算太难。

Iron Man 虽然剧情浅显，但也算说圆了一个浪子回头的故事，还顺带提了一下 Tony Stark 是否有一颗心的问题。但 Jon Favreau 也像 Tony Stark 一样不按牌理出牌，正当所有人都在期待Iron Man 2带来更深刻的剧情和更偏执的角色时，他成功地给了电影更好的视觉效果，更多的爆炸，更先进的科技和更炫目的演员阵容，却没有制造出一个像 Joker 一样复杂的角色。这种对比就解释了为什么影评人们这一次如此吝惜赞美之词。

但是，Iron Man 是不是像其他的漫画超级英雄那样，有那么多的童年阴影和心理问题可供导演拍一个“更有深度”的续集？Tony Stark 的自我复仇和救赎早在第一集中已经完成，他不会再像 Bruce Banner 那样，觉得自己是被侮辱和被损害的；也不会像 Bruce Wayne 那样始终处于对自己善恶的反思之中。在说出一句“I am Iron Man”之后，Tony Stark 已经卸下了几乎所有其他超级英雄都要背负的重担——在作为凡人的自我和被强加的英雄身份这两种认同之间的挣扎。再把那些多少有点人格分裂的超级英雄的自我怀疑和救赎套路生搬进这个系列，我想不是明智之举。

Iron Man 的魅力在于他的高调和特立独行，故事里安排的困境也要与这种特质相符。所以我们在 Iron Man 2 里看到的是一个孤身对抗世界的神一般的 Tony Stark。作为一个有肉身的神，他面临着被其他人崇拜着疏远的危险，更要提防那些虎视眈眈的弑神者和试图窃取其力量的模仿者。这个动机很难给观众以认同感，更难让人觉得这是一个说得过去的剧情动力，毕竟谁也没有真的孤身一人维护了世界和平。更要命的是，如果编剧顺着这样的思路走下去，给 Tony 安排一个类神的 Nemesis，哪怕是 Joker 那种级别的小神，也会让他们的对决变成诸神之战，那观众还不如去看 Clash of the Titans。这次的反角，还是一个试图把 Tony 拉下神坛的小人物。反角对 Tony 的神性的消解，Tony 在知道自己来日无多时的恐惧和疯狂，以及他最后从家庭获得力量的情节，虽然很难说是上集剧情自然的延续，但至少避免了剧情的失调和情绪的失控。这次的剧情动力也许不足，但却是为使观众接受 Tony 这个形象不得不做的牺牲。

上一集 Tony 的敌人就来自他的身边，而这次变成了来自俄国的威胁，不知道是不是编剧为了忠于 Iron Man 初创时期的冷战主题。跟上一集的中亚战场背景相比，这个设定显得跟现实生活更脱节。当然，从美俄关系出发也能写出很有张力的剧情，比如游戏 CoD: Modern Warfare。Iron Man 2 如果能再挖掘一下 Howard Stark 和 Anton Venko 在70年代的关系及其后果或许会让这个设定在今天显得不那么突兀。

二号反角的身份延续了上集的设定，还是无良的军火商，不知道编剧是否有继续埋汰这些形象复杂的死亡商人的意图，或者仅仅是为了让 War Machine 的出现顺理成章。但是加上 Ivan Venko 后，这两个人形成了与 Tony Stark 的有趣对照。当 Justin Hammer 跳着舞上台介绍自己的产品时，我不由自主地想到了试图模仿 Steve Jobs 的产品发布风格但是画虎不成反类犬的 Steve Ballmer。而影片开头 Ivan Venko 独自在车间加工盔甲的镜头也让人想起第一集里山洞中的 Tony Stark。这两个反角的存在提醒了我们手中握有先进技术的人是多么热衷于发明新的大棒而不是改良胡萝卜的种植方法，Tony Stark 本来也完全可能成为那样的人。这于是也让观众更容易对 Iron Man 产生认同感，虽然也让这个角色在第一集里的转变显得更突然且更不现实。如果说相信科技能让生活更美好的 Howard Stark 代表了对科学改善人类福祉的乐观，那么这两个角色无疑提醒了我们无视人类天性的科技发展带来的可怕副作用。

饰演两个反角的演员，Sam Rockwell 和 Mickie Rourke，虽然扮相迥异，都展现了他们近年来最好的表演，甚至让人觉得他们没有演 Joker 这种级别的反派（有派的反角）实在是太屈才。Mickie Rourke 饰演的 Ivan Venko 有表面上的疯狂，更有仿佛在不知不觉间流露的内心世界，甚至足以让观众在观影时站在他的立场上思考，虽然导演没有给他安排大段独白的机会。Sam Rockwell 的角色拿捏得很好，又是一个在说话间刻划了一个有故事的人的成功范例，同时又恰到好处地控制了这个角色与 Tony Stark 的关系，没有让他显得太具威胁或者太无足轻重，从而具有更多的发展可能性。

其他演员里，Robert Downey Jr. 再次证明了他是饰演这个角色独一无二的选择，Gwyneth Paltrow 也给了 Pepper 这个角色比第一集里更立体化的诠释，看 Tony 和 Pepper 这两个角色拌嘴是观看 Iron Man 2 最不能错过的乐趣。其他演员似乎也发挥出了自己表演的最佳状态，除了 Samuel Jackson 的表演太随意了一点，Scarlett Johannson 由于剧情限制不得不当了花瓶以外——但是她拍动作戏也是进影院的一大理由。

要说没有给演员足够发挥余地的原因，还是过于强大的演员阵容和像 The Hulk 的裤子一样塞得几乎要爆炸的剧情。除了连篇的动作戏，编剧还试图加进类似 Spiderman 2 里的英雄沉沦-回归，类似 Empire Strikes Back 的双反派联手，还有 Nick Fury 不时出现插科打诨，难怪所有非动作戏的剧情都好像是大餐中间送上的瓜子泡菜。但其实广受好评的第一集也有这个问题，只是上集里的非动作剧情串联得更好一些而已。作为漫画电影，Iron Man 2 必须提供更多的爆炸和更多的新奇技术，剧情的连贯上也就难免顾此失彼了。

但编剧至少在两个方面是成功的：对情绪的控制和节奏的应用。Rhodes 和 Tony 的一段打斗，看似跟所有酒吧斗殴一样无厘头，但避免了观众陷入消沉的情绪中，与后面 Tony 的重整旗鼓顺利地衔接起来。片子让观众几乎从头到尾都处在亢奋的状态中而不感到厌倦或疲劳，这是编剧最大的功绩。影片中大量笑料都是在几十分钟前铺下包袱，关键时刻一抖，娱乐效果很好。

任何电影都不能让所有人满意，一部仅仅在动作和演员阵容上加强，剧情还有所削弱的 Iron Man 2 也许会让不满的人更多，但是就像 Tony Stark 这个形象一样，一个不受传统改编电影规律羁绊的系列和编剧、导演为维持其风格作出的努力是值得肯定的。
