#+TITLE: 缺少人物一口气

听说武术界有句行话，叫做“内练一口气，外练筋骨皮”。练武不仅要强壮筋骨，内在的“练气”同样重要。如果没有“气”的支撑，筋骨再强健，皮肉再结实，也都不过是任人宰割的沙袋而已。

细细一想，这样的道理似乎也可以用来阐述武打电影中场面与人物的关系。我们区分武打和武侠电影，要看的是电影的剧情中是否体现了为国为民的侠骨和曲折辗转的柔情，若有，则可称为武侠电影，否则，似乎就应该归入武打电影。这样的分类方法，可能会给人造成一种错觉，那就是武打电影中人物的塑造并不重要，只要剧情让人热血沸腾，武打场面足够精彩刺激，就足以支撑起一部成功的武打电影。

但是武打电影真的是如此四肢发达头脑简单么？这几年来，以《卧虎藏龙》为代表的武侠电影逐渐式微，而武打电影在以甄子丹为代表的一代动作明星的带动下，又有逐渐兴盛的趋势。但是，并不是每一部武打电影都值得叫好，最近的片子里反差比较大的，要数《叶问》和《叶问2》。前者可算是一部成功的武打片，除了咏春拳、打日本人、打土匪、收徒弟这样群众喜闻乐见而又有些老套的戏肉，关键是电影塑造了叶问这样一个处事低调与世无争，但在时代大背景下不得不选择了抗争的形象，以人物带动剧情，成了这出戏内在的一口气。《叶问2》就少了一口气，编导试图用剧情来带动人物，结果只有洒民粹主义的狗血，观众觉得这个叶问外强中干，远没有前一集里宗师的感觉。

武打片也许不需要用大量笔墨来描绘侠骨柔情，但人物即剧情，要拍一部站得住脚的武打片，不塑造人物是不行的。成龙的武打片剧情也许千篇一律，但他每一次的插科打诨都是为了塑造一个能够笑对一切挫折又不屈不挠的小人物，所以我们二十几年后都记得香港警察陈家驹。甄子丹的《导火线》，打得比成龙的电影好看得多，但是你记得主角在电影里叫什么吗？

《打擂台》这个电影，筋骨皮是不缺的，光是那怀旧的片头就足以让每个看香港武打片长大的观众燃烧了，更不用说还有梁小龙和泰迪罗宾这样的重量级人物。片子武打很棒，笑料很多，要煽情有煽情，要剧情有剧情，更不用说男主角绝对是“外练筋骨皮”这句话最好的注脚。但是《打擂台》要塑造的人物是谁呢？不是只有一个背景故事的女主角，不是从头到尾都被人指点的男主角，也不是从不直接推动剧情的老拳师。只剩下阿成和阿淳这对师兄弟，虽然爱师敬师之情是很直白地表现够了，但也流于平面化，不足以支撑起剧情。更不用说这种男主角在日常工作中遇到的奇人也不应当起到主要人物的作用——难道《仙剑奇侠传》真正的主角应该是酒剑仙么？

《打擂台》里着力最多的人物，其实是罗新，且不说这么设置把主角置于何地，关键是让这个人物昏睡三十年的那段恩怨，会是多么好的剧情推动力，可是编导一点没用上，电影里甚至都没有明确说明庞青和罗新到底是什么关系。罗新一口气没有了，片子的剧情也就整个散掉了。没有内里的一口气，光练剧情和怀旧的筋骨皮，再让这个没有灵魂的躯体告诫大家“要打就打赢”，只会让人觉得错愕和失落而已。
