#+TITLE: 讲一个故事的数十亿种方法
#+AUTHOR: Haoyang Xu

#+BEGIN_QUOTE
    我们叫做玫瑰的这一种花，要是换了个名字，它的香味还是同样的芬芳。 ——莎士比亚《罗密欧与朱丽叶》第二幕第二场
#+END_QUOTE

而托马斯·福斯特说

#+BEGIN_QUOTE
    只有一个故事。我认为那唯一的故事，那个单一神话讲的是我们自己……
#+END_QUOTE

而在《玫瑰的名字》里，艾柯写道：

#+BEGIN_QUOTE
    我仿佛觉得，现在我写在纸页上的，就是你，不知情的读者，现在所读的，无非是一些拼凑起来的文集摘录，一首形象的颂歌，一篇无尽的字谜，不过是转述并重复那些残存的纸页上的片段对我的启示。我不知道是我一直谈论它们，还是它们通过我的嘴说出来。……不知道我所写的是否有某种含义，或者含义不止一种，而是很多，或者根本没有任何含义。
#+END_QUOTE

我们试图表达自己和理解别人的实践经验，不断向我们证明，文本的意义并不是文本的创作者所希望表达的意义，只有在读者的理解完成之后，文本才被赋予完整的意义。而读者这一边的理解过程，完全可能催生作者意想不到的新的意义。如果莎士比亚看到《纸牌屋》的演绎，他怎能不为这个新的理查三世和伊阿古拍手叫好，并像我们一样期待弗兰克未来的故事？但我敢肯定，他也同样会为我们不能理解400年前的他所要表达的某些观念而捶胸顿足。他也许会抓住托马斯·奥斯特玛雅的衣领，告诉他哈姆雷特与挪威王子福丁布拉斯的关系应该得到这样那样的表现。但这位导演，还有我们观众，会告诉他，我们会试图用哈姆雷特十六世纪的眼睛去看待剧本，但我们选择这样理解，是因为这样对二十一世纪的我们来说有意义。

一千个人心中有一千个哈姆雷特，这是强调读者对于文本解读的作用。它也许是被强调得太多了。只有一个莎士比亚，而且他是一个生活在十六世纪后半的诗人和剧作家，这是托马斯·福斯特试图向我们强调的。他认为，即使只是我们花几分钟就能读完的短篇小说，也是作者花费数天甚至更多的心力写成；在写作的过程中，作者会不断地进行横向思考，将他所读所见的通过笔下的文字传递给他想象中的读者。读者通过联系自己的记忆，探索文学作品中的象征，并发现作品中使用的模式，将更好地理解故事的含义，同时为自己的阅读增加多得多的乐趣。

这是一种建构主义和现代主义的文学方法论。读者被要求理解和记忆众多的典故和原型，以便理解作者用同样的典故和原型写成的小说，并用自己的记忆和经验作为水泥，和作品一同构建意义的大厦，或其中的一块预制板。在阅读经典和文学作品日渐成为时间上要求太高，经济上又几无回报的活动的今天，福斯特建议的方法似乎过于奢侈。当读者拿起这本书的时候，恐怕也会有同样的疑问：我为什么还要一本书教我如何读小说？为什么我不能按照自己的理解去读？或者更有主见一些的读者，会问为什么到了二十一世纪，我们不能用更加时髦的后现代的解构主义的方法去剖析一部作品。

一个不直接相关，但可以用来给福斯特辩护的事实是，工业文明除了让我们的生活节奏更快，更没有时间读书，也将“文本”的含义大大扩充了。即使你没有读过《圣经》，《埃及王子》和《低俗小说》也会让你对其中的某些片段略知一二。对互文性的探究并不需要限定在文学的领域。

“自己的理解”当然也受读者所接触过的一切文本的影响。但是这种影响是显式的还是隐式的却大有讲究。例如对《教父》的几篇书评，都不可避免地受到影片的影响，以影像化和形象化的笔调来谈论小说和人物，[1]而没有看到小说实际上是一个意大利人写意大利家庭如何被美国文化整合同化的故事。它和电影的大受欢迎是因为当时的美国处于一个传统家庭受到各种社会风潮冲击的时代。[2]缺少这些理解，《教父》是个很棒的黑帮故事，但小说远没有电影来得紧凑有趣。而如果把《教父》当成一部家族史的后期篇章，读者就更能对《教父 II》里这个家族的分崩离析感受到普佐和科波拉希望我们感受的沉重，而不是把迈克尔看作家族危急关头的救主。不可否认，当寻找象征、模式和上下文成为习惯，它也不可避免地会影响我们利用直觉理解作品的能力，和作品带给我们的原始冲击。福斯特自己也在书里抱怨，“我们这帮文学教授饱受记忆之累……想不这样做都不行”。但对于小说，一种可供反复咀嚼的文本，第一印象和直觉的冲击并不太容易受到发现模式的影响，而理解象征与模式更可以让我们理解小说的深层含义。

至于解构主义的解读，福斯特抱持否定的态度。福斯特认为解构主义者读小说不过是把在整体上才能完全体现意义的作品拆得七零八落，去研究里面的零件，比如某个词语的二义性，然后得出与文本不甚相关的结论。将解构主义进行极端的理解，我们甚至可以认为文本的意义只与读者对词语的理解有关。他所指的解构主义似乎不同于德里达的解构主义。德里达仍然主张把词句放在文本的解构中去理解。福斯特所反对的，大概是耶鲁学派的解构主义，或曰后结构主义文学批评。该学派的领军人物德·曼认为文本本身并无意义，文学系所做的不过是用心理、政治、历史等等学科的知识，试图赋予文本以意义。有关文学的理论，不过是掩饰文本所含有的不可决定性——也就是不可解读性，的手段。

福斯特的主张更与我们的直觉一致。正如文学作品里提到平常的吃饭一事，必然有它的用意，作者们想必不会为了写下一些本身没有含义的文字，而大费周章地谋篇布局。德·曼提到的不可决定性，或许正反映了读者与作者之间必然存在的理解断层。他用来证明这种不可决定性的诗篇，济慈的《海伯利安的陨落》，可是带着被这样解读的预期写成的？我想不是这样。理解文学作品，也许还是要首先尊重作者表达的意愿，和语言作为表达工具的有效性，预设文本是一种有效的意义载体。对于普通读者来说，部分地认同德里达的解构，即应当考虑到作者的意图，同时承认作者有“言外之意”的可能就好。

但如果读者又是作者，福斯特对作者意图的淡化就让他们感到不适。我在前文里也多次表示了对作者意图的猜测和好奇之心。福斯特却将文本作为作者观念最忠实的代言人。如果大家都像蒙田和卢梭那样诚实就好了，可是我们如何得知他们真的诚实？无疑福斯特以文本为根本的方法更加可操作，我们只要承认已经写成的文本就是既成的事实，是那个唯一的故事的一部分就好。但这也就是承认还有千亿个心灵，它们所在想的我们完全无从得知。人可以想一套说一套，说一套做一套，但至少我不能一边在脑海里想“写到中午了好饿啊”，而不在这篇书评里留下同样的文字。只有在笔落在纸面，手指按下键盘那一瞬间，作者的所想是我们可以去感知的，这也许就是写作和阅读的意义吧，不然不同的心灵还有什么办法去交流？

只有一个故事，这仍然是理解福斯特的文学观和方法论的关键。正如人类只有一套从最早的单细胞动物遗传和演变至今的基因，我们也只有一套迷母，用来描述人性的互动产生的无数喜怒哀乐。基因的变异在对环境的适应中被保留下来，唯一的故事则随着时代的变迁不断被赋予新的面貌。所以象征物会不断改变，在中国是王母娘娘，在希腊则是赫拉，背后的原型却还是那个单一神话。我们一层层抽丝剥茧去接近这个单一神话，目的不是那个我们早已熟稔的唯一故事，而是看它“用怎样的‘钹’来弹奏”。正如我们感兴趣的是俊美的面容而不是下面的骷髅，在文学里，看懂另一个人怎样讲故事，比看懂这是一个什么故事更有意义，可为了做到这点，我们又不得不尽量去理解每一层文本和前文本再到象征再到模式的含义，直到接近最下面的原型和骨架。如此说来，福斯特提出的方法，既然是从只有一个故事的假设出发，自然也可以应用到中国文学甚至“网络文学”中去，只是读懂它们需要一套不同于西方文学的知识体系。

这不是一个简单的要求。虽然我是中国人，却不敢说对《山海经》比对《圣经》更加熟悉。或者，这意味着要读懂东野圭吾，我们还得从星新一、江户川乱步一直上溯到紫式部？福斯特说，并不是这样，我们并不需要成为文学教授而读懂小说。从我们自己的知识和记忆，我们就能理解一个故事，毕竟故事只有一个，每个人有一种读法。即使不知世界上有日本，东野圭吾所写的情感冲突也能让我们从故事中得到乐趣。但是如果我们能从象征和模式的角度去理解《白夜行》，而非仅仅欣赏它的情节，阅读会给我们带来更多的乐趣。我想福斯特所说的乐趣可以用两个不同的英文单词来表述。在描述不加思索地读小说，随着情节又哭又笑的乐趣时，他用的或者想的词是“fun”，而在读懂一篇小说背后真正的故事时，他用的或者想的词是“joy”。Joy 描述的是我们在为我们的时间（也就是生命）创造和赋予意义时，所体验到的那种幸福，它来源于一定的努力和思索，还常常伴随着不少的失落和烦恼，但只有它能够和不愉快的记忆一起被保留下来。[3]一个故事有数十亿种读法，而我读过的一切文本的记忆，将决定我如何读这本书。我在读的这本书，又将影响我对过去读过的一切的记忆和感受，这种与作者共谋，而又独一无二的体验，能够带来持续和改变一生的乐趣。给玫瑰以名字，给文本以意义，给阅读中的自己以幸福吧。

Footnotes:
[1]
《卫报》：http://www.theguardian.com/childrens-books-site/2014/feb/09/review-the-godfather-mario-puzo ，不知道为什么放在儿童书里。
[2]
What Puzo Godfathered 40 Years Ago http://www.wsj.com/articles/SB10001424052970204886304574308603266273652
[3]
所以《头脑特工队》里的主角叫 Joy 而不是 Fun，是很有道理的。
