#+title: 有没有被压迫和被损害者的地理学？
#+author: Haoyang Xu

2006年，堪萨斯大学的地理学家 Peter H. Herlihy 带领学生来到墨西哥瓦哈卡州的一个萨波特克人小村，Tiltepec。他们的目标，是帮助这些原住民制作一张自己的地图。

为什么一个美国人要跨越两千多英里的距离，跑到墨西哥一个小小的原住民村子，帮助当地人制作地图呢？Herlihy 知道当地人会有这样的疑问。他解释说，地图一向是殖民主义和权力的工具。Herlihy 的老师，Bernard Nietschmann，曾经说过：「用地图从原住民手中夺取的土地，比用枪炮夺取的还要多。」[1]

在18和19世纪，殖民者带着测绘工具，制成地图，然后在上面一划，就定下了自己的势力范围，以此再去和其他的殖民者讨价还价。而原住民因为没有地图这一工具，也没有测绘的技能和手段，只能任自己的土地被不费吹灰之力地划走。现在的非洲地图和美国地图上，那些整齐的、平行于经纬线的国界和州界，就是这个过程活生生的证明。

反过来说，Herlihy 认为，现在地图也可以成为原住民表明自己对土地的权力的工具，帮助他们保存对自己土地的知识。当年，正值墨西哥政府的土地改革即将进入瓦哈卡州和 Tiltepec 所在的 Sierra Juárez 山区之际。土改的主要内容，是将原有的集体土地的产权明晰化，为土地的私有化和市场化铺路。

1992年，随着北美自由贸易区[协议]（NAFTA）的签订，总统卡洛斯（Carlos Salinas de Gortari）所领导的政府终于下决心对土地制度进行改革。改革的目标主要包括：解除强加在农村集体土地上的种种限制（比如不得出让、租赁或者抵押等），通过确权和登记明晰集体和集体成员的土地产权，增强妇女的土地权利，完善土地市场的功能等等。
具体来说，1992年的改革主要包括以下几个方面：

（1）政府首先对村社的土地重新进行测量，然后依据测量结果对村社的土地总量、农场内各个家庭和家庭成员的土地份额（主要是耕地和居住用地）进行登记；[2]
……
萨波特克人担心政府随意划定自己的土地界限，而 Herlihy 告诉他们，自己来这里，正是为了帮助他们把自己对土地的知识和权力落实到地图上，在与政府的谈判中不至于吃亏，或者由于政府缺乏对当地文化的了解而进一步被边缘化。他还告诉 Tiltepec 的村民，自己已经有在墨西哥城附近几个村子开展工作的经验。经过18个月的反复说服和磋商，在2006年夏天，Tiltepec 村民讨论了两个小时，决定给 Herlihy 的团队开绿灯。虽然还是有人怀疑 Herlihy 是给墨西哥政府提供情报的，但他终于可以带着学生开展制图工作了。

Herlihy 一行使用了一种称为参与式制图（Participatory Mapping）的方法。在取得村民对他们工作目标的不反对意见后，他们首先拿出一张白纸，让村民根据自己对村子布局和周围边界、地标的认识，画出一张粗略的村子布局图。之后，他们和村民一起，带着这张地图走街串户，上山下田，让陪同的村民讲解，这里是村子创始者的故居，那里是一个有神圣意义的山洞……并请村民用 GPS 设备把这些地方的座标记录下来。

经过从2006年到2008年，总共100多天的现场工作和无数的内业工作后，[1]Herlihy 带着完成的地图回到 Tiltepec。这张地图是当地人数百年来口传心授的地理知识的集中呈现。地图上标注了村民居住地具有历史和文化意义的房屋、纪念物，也有村子附近对村民生活至关重要的河流的名称。[3]Herlihy 等人正是在制作地图的过程中，才发现当地人对同一条河流的不同河段有不同的称呼。[1]如果没有这份地图，我们永远也不可能知道。

然而，在 Herlihy 展示完地图之后，立即有人发难。他们指责 Herlihy 的团队是受美国地理学会（American Geographical Society）的委托工作，而美国地理学会又拿着美国军方外国军事研究办公室（FMSO）的经费。Herlihy 的研究项目主页上只有英文，村民们看不懂。墨西哥人问：美国军方安的什么心？

Herlihy 等人拼命解释，项目被 FMSO 资助的事实，当初介绍项目的时候，第一张 PPT 上就提到了，他们是取得了村民的知情同意后才开展工作的。但是很快事情就闹大了，不仅村民拍视频声明他们根本对 FMSO 的事情不知情，美国国内的民权运动家和地理学者也加入了批评这个项目的行列。Herlihy 的学生为此有很长一段时间都很难找到教职。[1]

这个尴尬的事件实际上暴露了地理学的一个旧创。现代地理学的诞生与19世纪殖民主义的全球化，以及随之而来的探索热潮，有不可分割的联系。探险家们为了荣誉和名气，纷纷航向过去西方人不能或不愿前往的「不毛之地」，记录下自己对地形地貌、风土人情的见闻，再发一番对「土著」的议论，或者与其他地方做一番比较，这就成了地理写作的雏形。地理学的发展和殖民主义力量的扩张是分不开的。

进入20世纪后，地理学的理论有了发展，变得更加系统和全面，它的殖民主义色彩也随着殖民热潮的退却而逐渐减淡。但地理学者确实像其他的社会科学研究者一样，始终未能摆脱与政治和军事的联系。政治家和将军们深知，要管理好一个地方或打赢一场战争，不能不了解地理，于是他们都把地理学家当成座上客，甚至深入战区的顾问。有时候这种关系以吊诡的形式出现。布什的伊拉克战争不得人心，但为了维持占领，Petraeus 设计了「人类领土」（Human Terrain）这个概念。地理学者们普遍反对入侵伊拉克，但他们认为 Petraeus 的战略有助于减少士兵和平民伤亡，因而愿意为它背书。Herlihy 在回应关于他和军方的关系的质疑时，曾经写道[4]：

The human terrain concept, however controversial, sits at the core of our discipline and recognizes that the same geographical understanding needed to conduct wars is also essential for avoiding them in the first place.
美国军队也是以类似的逻辑，阐释在世界各地驻军和军事干预的正当性的：从人道主义出发，减少伤亡。地理学家如果不能意识到，地理的方法和知识对于政治和军事力量的投射目的完全没有干涉的能力，就随意接受与权力的合作，未免就显得过于天真。
Herlihy 在 Tiltepec 绘制的地图最终被从网上删除。少数几份保留在村子里的纸质地图，被用来向孩子们和政府官员说明村子周边的地名。据说在其他村子绘制的地图，在处理土地纠纷时确实起了一些作用。

我们对于 Herlihy 的目的并不需要有太多怀疑，他很可能是带着最良好的愿望来开展在墨西哥的工作的，而且他的成果确实促进了当地人对自身的了解，并让他们的诉求更容易被当地政府听到。但是 Herlihy 和其他任何人都无法控制这些方法和成果被用于什么目的。和历史被当成小姑娘随意打扮一样，地理学缺乏一种统一的、放之四海皆准的理论基础的事实，使得价值判断成为学科道德最根本的守护者。

那么有没有一种天然地站在被压迫和被损害者一边的地理学呢？马克思主义批判地理学和后殖民主义地理学曾被寄予这种希望，但社会的复杂性摆在那里，如何定义被压迫和被损害者？他们的哪些权益更为重要？哪些权益可以做一时和长久的牺牲？关注弱势群体的地理学得到的结论，也可以在另一时空、另一种诠释下伤害这个或其他的弱势群体。这也是为什么试图为地理学建立恒久不变、广义适用的理论实际上非常危险的原因。地理学要为过去的殖民主义历史赎罪，必须依赖地理学者认识到学科在理论和方法上的不完备性，权衡研究对各种利益相关方的影响，并在不断增加对地方了解的基础上，推进学科和相关伦理的进步。

参考文献

The Oaxaca Incident - An American Researcher. A Mexican Village. The U.S. Military. What Could Go Wrong?
墨西哥20世纪的农村土地改革及其对中国的启示 - «ק¸ח20¼µ©´וµ¸¸ן¼°ה¶¹תµפ¾_‏·¨¾_¹ת‏ר
Participatory Mapping Powers Patrimony - http://www.csuchico.edu/~sbrady/Mapping209.pdf
Force multipliers: Geography, militarism, and the Bowman Expeditions - http://academic.evergreen.edu/g/grossmaz/BryanForceMultipliers.pdf
