#+TITLE: Live (not so) long and prosper
#+AUTHOR: Haoyang Xu

看 J.J. Abrams 重启的 Star Trek 系列，有 Leonard Nimoy 出场，惊喜之余不免感叹：在旧系列中精神头十足的 Spock，老来竟然显得如此憔悴，不知道还可以演几部 ST？

所以今天早上看到 Nimoy 去世的消息，竟然一点惊讶也没有。英语世界的媒体都在发表给他的悼文，充满了敬意和怀念，似乎也没有惊讶和悲痛之意。NYT 的视频里说他“lived long and prospered”, 可算是对他这一生的一句不甚严肃，但不失精炼的概括。

Leonard Nimoy 终年83岁，他在这一生中演过舞台剧，当过主持人，当过兵，演过电影和电视剧，给动画片配过音，还写了两部 Star Trek 电影的剧本。他的生命的长度对他生命的宽度和多样性来说恰恰好：长到足够让他在每一方面都产生和留下足够的成果，而又短到尤其精彩和充实。

加缪在他的论说文《荒诞的人》中这样写演员：“在一切光荣中，他的光荣是最为短暂的……一个演员可以有三个小时成为伊阿古或阿尔塞斯特，费德尔或格罗塞斯特……在这三小时内，他要把一条走不通的路走到底，而这条路观众席上的人要走整整一生。”

加缪又写道：“有一点儿想象力就足以感觉到演员的命运意味着什么。他是在时间中一个一个地创造他的人物。他是在时间中学会控制他们。他越是体验过不同的生活，他就越能和他们分开。必须死在台上和世界上的时候到了。他体验过的东西面对着他。他看得清清楚楚。他感到这场冒险所具有的令人痛苦、不可替代的东西。他知道，他现在可以死了。老演员们是有隐退的居所的。”

也许 Nimoy 这样长寿而多产的演员更加令人羡慕。他扮演 Spock 的时间，总共加起来也许就100小时上下，但这足以让他以 Spock 的身份去充实一种生活，体验和表达命运，“为重新发现自己先失掉自己”。更不用说他还出演了其他的角色。这是何等丰富的人生！

但角色对演员自身生活的助益终归是有限的。角色的生命经验会随着一次次的表演渗入演员自己的生命，但演员也只有一次生命可供这样的渗透。所以，好的演员通过尽力深入并非他本人的生活而征服了命运，这样的角色有一次也够了。而非演员的人通过尽力深入自己的生活，追求那明知不可能但永恒的胜利，也就实现了所以为人的目的。甚至从加缪的表述反推，这样的人生不必太长，能够活三小时，和活三百年，并没有什么区别。

如果再没有台词可说，再没有动作可作，演员因为留恋舞台而继续逗留便是不合常理的和无益的。假如生活是对命运的反抗，那么无力反抗之时便应当是生活结束之日。或许正是因为意识到这一点，有人提出他只愿意活到75岁，在此之后，他将不再做出任何试图延长生命的举动。

我有心效仿，但也深知对生命的留恋的强大，特别是当自己还有事未完成而眼见死期将近的时候，谁不会试图再多给自己一点时间？或许一点虚无主义是必要的：生活是不抱希望的抗争，在 todo list 或者 bucket list 上多划一个勾，并不意味着生命更有价值。即使 Leonard Nimoy 只演过 Spock 一个角色，他对这个角色命运的诠释已经证明他接近了对永恒和自身命运的胜利。
