#+TITLE: Thomas Ostermeier's interpretation of classics
#+AUTHOR: Haoyang Xu
#+DATE: 2016-03-02

I am reading a lot about Thomas Ostermeier and his directing work today, as we are planning to introduce his plays to more people in developing countries. Or some State-Capitalism oligarchies, anyway. I think his specialty is seeing the human condition and anxiety, where other directors may only see issues. A descendant of Brecht's tradition, he looks into plays with a perspective focusing on the alienation of men by capitalism. He thinks that capitalism is built on a lie, that although it only pursues profit, it must maintain the coherence of the society by pretending to uphold certain values such as family, community, caring for children, etc. These values are actually powerless when compared to the real value held by the capitalist system. 

When individuals feel weak and defeated by the system, they naturally go to family and friends for love and solace. But these are powerless and they cannot solve these individuals' anxiety. This is a theme identified and explored by Ostermeier time and time again in his interpretation of Ibsen's play. In today's economic situation, Ibsen's plays are never so relevant, so Ostermeier claims.

Is there a lie in capitalism? If we consider it only a form of organization of economy, the answer seems to be "no". As long as we only let capitalism organize production and consumption, our society can be truly run by philosophical or religious values. But if the infrastructure empowers profit-seeking institutions, things become complicated.

In my country, where political power is largely dependent on the heritage and other political support, capitalism seems to be the main factor in people's value system. The reason may be that for most people, politics is never an option. This makes the upward moving possibilities even fewer than in India (whose caste system is peculiar enough, and may affect the society's final composition, but that's another story). And capitalism values may be held more feverishly than in, say, the UK. How would an Ibsenian situation unfold in a family here? 
