#+TITLE: SOHO people: you need a metronome event in your life
#+AUTHOR: Haoyang Xu

People who sit a lot in front of a desk or a computer should consider jogging. Not only because it is good for your health. Jogging drives many other actions in your life, before and after the event itself. To jog you have to sleep early, and probably rise early too. You have to eat breakfast. Later you have to take a bath and wash your workout clothes. Combine these with a regular schedule, you suddenly find that you maintain good habits, keep great hygiene, and do laundries regularly, without considering them chores.

I call jogging a kind of metronome event. It gives your life a pace and many great things can jump on its bandwagon. If you don't jog, you can find other things as the metronome event that suits you. How about a weekly eating out? Or a biweekly stroll around the campus/block where you live? Come up with one, then organize your routines around them.

But too many metronome events will make them all look like chores again. So pick one and stick to it.
