#+TITLE: Zootopia
#+AUTHOR: Haoyang XU
#+DATE: 2016-03-11

It's been a few days since I watched the movie. I decide to give it a 5/5 for its slick execution of a feature animation that discusses complex issues such as gender and races while maintaining an innocent look. 

One way to reduce the fun watching the movie, I think, is to try to assign each animal species/group you see to a category of people, or a stereotype, in real life. You just need to realize the city is complex and not perfect, and all kinds of agendas are affecting people's communications and attitudes. 

The movie successfully portraits the way we deal with race problems in a very realism way. Judy wants to do the right thing and treat people (animals are people) according to their characters, not races, but her fear buried deep inside makes her say things under pressure, which she regrets. Such level of psychology nuance is unseen in any Disney animations before. I think /Inside Out/ comes close and has teached the playwrights one thing or two.
