#+TITLE: 由独立游戏的兴衰想到的
#+AUTHOR: Haoyang Xu

各种艺术形式最初都是一小撮人的专利，而技术进步会将这些艺术形式带到每一个心智正常的人的手中。在这个阶段，不可避免地会看到采用这些表达方式的作品的整体水平出现剧烈的下滑。这带来一种“可见性偏见”，让人容易因为平庸甚至低劣作品的常见而对行业的整体状况失望。

在游戏市场令人失望的外表下有这样的可能：虽然满眼看去都是质量低劣的模仿作品和单纯满足感官刺激的游戏，但实际上有更多有趣的创意变成了高质量的产品。

真正的危机在于是否有足够的人去发现这些珍珠，正如这篇评论所描述的，当一种艺术形式随着技术的发展变得可以大规模生产，作品的平均质量往往降低，同时降低的还有人们的期望值。

当顾客只看到大量的还过得去的游戏是广告支持的，他们对花10美元买一个游戏就不再感兴趣。而开发者如果为了迎合市场而开发低成本、广告支持的游戏，资源和潜力就会被浪费，而高质量的游戏更难被发现。一个向下的螺旋。

我抱持的一个看法是，今天专职卖文为生的作家不应该存在。不管是什么样的写作天才，都无法持续地依靠写作维持生计。对于个人作者来说，想法和需要表达的情绪是有限的，愿意支持自己写作的人也是有限的。当最初的创意和想法被利用完之后，这个作家能怎么办呢？要持续与出版社的合作关系，和获得持续的稿费收入，作者只有去重复自己。同样地，独立的游戏开发者也几乎不可能以自身的创意不断地创作游戏并维持生计。

独立游戏开发者开发出一个好游戏，所获得的收入就能让它生活无忧，或者至少持续到下一个好游戏的诞生，这样的时代已经过去了，正如莎士比亚的时代已经过去了一样。留恋这个时代的结果只能是被迫地重复自己或者剽窃别人的创意，让 App Store 里充斥垃圾。

组团，结队，成立一个公司，既是“靠游戏挣钱”这个命题的解决办法，也是新问题的来源。一群人可以更快地想出点子并实现，但与其他公司的竞争很快也会使它们寻求捷径：剽窃其他平台和开发者的创意，牟利，并转向下一个利润增长点。

是的，所以我同意这篇文章的观点，即个人游戏“开发者”这个群体正在消失，被公司和个人“爱好者”所取代。在其他艺术形式的发展史上，这个过程也曾出现。对于文学、电影，建制化的生产和发行方式已经边缘化了爱好者群体，但互联网的长尾效应正在改变“爱好者”创作在这些领域的地位。

这一改变的前提是，人们有通过欣赏其他艺术作品和领域内杰作而培养出来的品味，能够自发地寻找和发现优秀的作品，或者更能打动自己的作品。这个过程在游戏开发的长尾里似乎就少见和困难得多。这与我们评价游戏的标准有关。特别是在手机游戏领域，标准单一得可怕。上一个人人都在玩的游戏，是2048？在它之前呢，Flappy Bird？它们都令人上瘾。但“上瘾”什么时候成了对自我表达和艺术的评判标准？

我想这便是为什么 #GamerGate 运动代表的那种对游戏的单一价值观不应该被鼓励，因为它阻碍了游戏作为一种艺术和表达方式的成熟。我想这也意味着好的游戏开发者应该是更乐于接受多元文化并有批评能力的人，虽然，不无遗憾地，它们不一定是最风光和最能赚钱的一群人。
